server:
  port: 10002
eureka:
  instance:
    metadataMap.zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-east
    service-url:
      zone1: http://cdh6:8761/eureka/,http://cdh6:8762/eureka/
      zone2: http://cdh6:8763/eureka/,http://cdh6:8764/eureka/
    availability-zones:
      region-east: zone1,zone2

