zuul:
  retryable: true #开启重试，D版之后默认为false，需要手动开启
  ribbon:
    eager-load:
      enabled: true #开启饥饿加载

  SendErrorFilter:
    error:
      disable: false
    host:
      max-per-route-connections: 1024
      max-total-connections: 1024
  routes:
#    zuul-gateway:
#      path: /client/**      #将所有 /clent 开头的URL映射到client-a服务中心
#      serviceId: client-a
    client-a:
      path: /client/**
      serviceId: client-a

  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000
  ratelimit:
    key-prefix: zuul-ratelimit    #按粒度拆分的临时变量key前缀
    enabled: true                 #启用开关
    repository: REDIS             #key存储类型，默认是IN_MEMORY本地内存，此外还有多种形式: IN_MEMORY 、REDIS、、
    behind-proxy: true            #表示代理之后
    default-policy-list:          #全局限流策略，可单独细化到服务粒度
      - limit: 2                      #在一个单位时间窗口的请求数量
        quota: 1                      #在一个单位时间窗口的请求时间限制
        refresh-interval: 3           #单位时间窗口
        type:
          - user                          #可指定用户粒度
          - origin                        #可指定客户端地址粒度
          - url                           #可指定url粒度
          - httpmethod
    policy-list:
      client-a:          #特定服务的路由
        - limit: 10               #可选 - 每个刷新间隔窗口的请求数限制
          quota: 1000             #可选 - 每个刷新间隔窗口的请求时间限制（以秒为单位）
          refresh-interval: 60    #默认值 (in seconds)
          type:                   #optional
            - user
            - origin
            - url
#        - type: #optional value for each type
#          - user=anonymous
#          - origin=somemachine.com
#          - url=/api #url prefix
#          - role=user
#          - httpmethod=get #case insensitive

##### Hystrix默认超时时间为1秒，如果要上传大文件，为避免超时，稍微设大一点
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  eureka:
    enabled: true
  #重试机制配置
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 2 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: true
  #禁用HttpClient并开启OkHttp
  httpclient:
    enabled: false
  okhttp:
    enabled: true

