server:
  port: 8081
spring:
  application:
    name: provider-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:cdh6}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
#  security:
#    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream